// This file is generated by Prismic local builder. Update with care!

export { default as Header } from './Header'
export { default as HomeContactSection } from './HomeContactSection'
export { default as HomeHeroVideo } from './HomeHeroVideo'
export { default as HomeSectionPresta } from './HomeSectionPresta'
export { default as HomeTextSection1 } from './HomeTextSection1'
export { default as MegaMenuImg } from './MegaMenuImg'
export { default as Slider } from './Slider'
export { default as SubHeader } from './SubHeader'
