// This file is generated by Prismic local builder. Update with care!

export { default as Header } from './Header'
export { default as HomeHeroVideo } from './HomeHeroVideo'
export { default as HomeSectionContact } from './HomeSectionContact'
export { default as HomeSectionPresta } from './HomeSectionPresta'
export { default as HomeSectionPrestaCat } from './HomeSectionPrestaCat'
export { default as HomeTextSection1 } from './HomeTextSection1'
export { default as Slider } from './Slider'
